Рубежный контроль №2 (без тестов)
go-park-mail-ru/2019_1_The-Recovery-Team pull request #2
Opened 2019-04-13 19:56 UTC by ZorinArsenij

#### Чек-лист:
- Есть middlewares, в которые вынесена логика по обработке паник, проверки авторизации, cors и логирование
- Вся информация о пользователях и пользователиских сессиях хранится в БД
- Используются вебсокеты. Через вебсокеты происходит real-time взаимодействие с сервером
- Есть разделение игроков по комнатам и работающая игровая механика

2019-04-14 13:00 UTC, ghost requested changes

2019-04-14 13:00 UTC, nd-r commented on go.mod
> +module sadislands
лучше называть полным именем github.com/..../sadislands, примеры у тебя есть ниже

2019-04-14 13:00 UTC, nd-r commented on internal/delivery/http/rest/handler/unmarshaler/json.go
> +	err = easyjson.Unmarshal(body, s)
https://godoc.org/github.com/mailru/easyjson#UnmarshalFromReader

2019-04-14 13:00 UTC, nd-r commented on internal/infrastructure/repository/postgresql/profile/profile.go
> +		case err.(pgx.PgError).ConstraintName == "profile_email_key":
а если тут не pgx.PgError?

2019-04-14 13:00 UTC, nd-r commented on internal/infrastructure/repository/postgresql/crypto.go
> +		{
для чего здесь { }

2019-04-14 13:00 UTC, nd-r commented on internal/infrastructure/repository/memory/game/game.go
> +	r.TotalM.Lock()
для такого есть atomic
https://golang.org/pkg/sync/atomic/#AddInt64

2019-04-14 13:00 UTC, nd-r commented on internal/domain/game/room.go
> +	ctx, cancle := context.WithCancel(context.Background())
cancle

2019-04-14 13:00 UTC, nd-r commented on internal/domain/game/game.go
> +	RoundTimer  *uint64           `json:"roundTimer,omitempty"`
я так понимаю, что вы юзаете указатели для того, чтобы понять передали ил вам значение или нет. Если да, то для этого есть пакет opt. https://github.com/mailru/easyjson/tree/master/opt

2019-04-14 13:00 UTC, nd-r commented on cmd/server/main.go
> +	_ "sadislands/docs"
дублируется

2019-04-14 13:22 UTC, ZorinArsenij commented on internal/domain/game/game.go
> +	RoundTimer  *uint64           `json:"roundTimer,omitempty"`
Теперь буду знать, что есть такая возможность. Но к сожалению, мы вряд ли сможем воспользоваться ей в данном случае, т.к. engine, который работает со state транспилируется в js c помощью gopherJS) Именно поэтому мы не используем внутри engine сторонние библиотеки.

2019-04-16 15:02 UTC, ZorinArsenij commented on go.mod
> +module sadislands
Исправил в d6b3d2f

2019-04-16 16:20 UTC, ZorinArsenij commented on internal/delivery/http/rest/handler/unmarshaler/json.go
> +	err = easyjson.Unmarshal(body, s)
Не знал, что есть такая функция. Удобно. Исправил в 338dc8c

2019-04-16 16:22 UTC, ZorinArsenij commented on internal/infrastructure/repository/postgresql/profile/profile.go
> +		case err.(pgx.PgError).ConstraintName == "profile_email_key":
Будет не очень хорошо. Поправил в a0c543a

2019-04-16 16:25 UTC, ZorinArsenij commented on internal/infrastructure/repository/postgresql/crypto.go
> +		{
Можно и без них. Поправил в 855b03a

2019-04-16 16:26 UTC, ZorinArsenij commented on internal/infrastructure/repository/memory/game/game.go
> +	r.TotalM.Lock()
Везде его использую, а тут забыл поправить. Исправил в 8239a0a

2019-04-16 16:26 UTC, ZorinArsenij commented on internal/domain/game/room.go
> +	ctx, cancle := context.WithCancel(context.Background())
Поправил в 69e6598

2019-04-16 16:26 UTC, ZorinArsenij commented on cmd/server/main.go
> +	_ "sadislands/docs"
Поправил в 69e6598

2019-05-29 12:28 UTC, merged