Рубежный контроль №3
go-park-mail-ru/2019_1_The-Recovery-Team pull request #3
Opened 2019-05-04 17:50 UTC by ZorinArsenij

- Можно поиграть в мультиплеер
- Есть микросервисы, которые общаются друг с другом по grpc
- К проекту прикручен мониторинг через prometheus и можно посмотреть графики по сервисам в grafana(хиты на API с разбивкой по статусам ответов, количество активных комнат/игроков в игре)
-  Нет захардкоженных урлов/логинов/паролей. Все хранится в конфиге, передаётся в переменной окружения (к сожалению, пока без Vault)
- Проект покрыт тестами минимум на 65%

2019-05-07 18:35 UTC, ghost requested changes

2019-05-07 18:35 UTC, ghost commented on cmd/server/main.go
> +	log.Print(http.ListenAndServe(":"+port, profileApi.Router))
а чего ж logger, err := zap.NewProduction() не заюзали?

2019-05-07 18:35 UTC, ghost commented on cmd/service/chat/main.go
> +		log.Println("pgx connection close failed", err)
Лучше для ошибок юзать log.Errorf, чтобы разделять ошибки от инфо логов

2019-05-07 18:35 UTC, ghost commented on cmd/service/game/main.go
> +package main
почти копипаста же chat/main.go

2019-05-07 18:35 UTC, nd-r commented on cmd/service/game/main.go
> +	metric.RegisterTotalRoomsMetric("game_service")
почему бы вам при создании метрики не делать MustRegister?

2019-05-07 18:35 UTC, nd-r commented on cmd/service/profile/main.go
> +package main
где-то я уже это видел

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +		return &CreateResponse{}, err
return nil, err

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +		return &CreateResponse{}, err
и так везде

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +	return &Nothing{}, err
Что за Nothing? Почему нельзя вернуть просто err? Почему нельзя вернуть interface{}?

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +	return &Nothing{}, err
anyway return nil, err

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +	return response, err
return response, nil

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +	return response, err
В го есть соглашение: если есть ошибка -- возвращаемому значению верить нельзя. Если ошибка nil, то возвращаемым значением можно пользоваться. Тут как раз успешный выход из функции, а значит return response, nil.

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +	response := &GetResponse{
Тот самый момент, когда короче -- лучше
https://www.reddit.com/r/golang/comments/8wxwgv/why_does_go_encourage_short_variable_names/

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/profile/profile.go
> +func (s *Service) GetByEmail(ctx context.Context, in *GetByEmailRequest) (*GetResponse, error) {
не изменяете нигде in
Зачем его передавать по указателю? Если оптимизация, то она скорее всего преждевременная. Лучше всего сохранить читаемость кода (передавать по указателю -- для изменяемого, по значению -- для неизменяемого)

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/grpc/service/session/session.proto
> +
что за лишние строки?

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/http/rest/api/game/handler/game.go
> +		prof, err := (*profileManager).Get(context.Background(),
зачем тут (*profileManager)?

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/http/rest/api/game/handler/game.go
> +		prof, err := (*profileManager).Get(context.Background(),
можно же просто profileManager

2019-05-07 18:35 UTC, nd-r commented on internal/app/delivery/http/rest/middleware/middleware.go
>  var allowedOrigins = map[string]interface{}{
если сделать map[string]bool, то можно просто писать if allowedOrigins[domain] {}

2019-05-07 18:35 UTC, nd-r commented on internal/app/infrastructure/repository/memory/chat/chat.go
> +		case chat.InitGlobalMessages:
нужно умещать функции на один экран (40 строк это прям максимум)

2019-05-12 14:07 UTC, ZorinArsenij commented on cmd/server/main.go
> +	log.Print(http.ListenAndServe(":"+port, profileApi.Router))
Не досмотрел. Поправил в 0b86ac1

2019-05-12 14:08 UTC, ZorinArsenij commented on cmd/service/chat/main.go
> +		log.Println("pgx connection close failed", err)
Наверно log.Fatal? Просто не нашел log.Errorf. Поправил с использованием log.Fatal в 9dc55ba

2019-05-12 14:09 UTC, ZorinArsenij commented on cmd/service/game/main.go
> +	metric.RegisterTotalRoomsMetric("game_service")
Поправил в 9934744

2019-05-12 14:11 UTC, ZorinArsenij commented on internal/app/delivery/grpc/service/profile/profile.go
> +		return &CreateResponse{}, err
Что-то не выходит так сделать. Это ведь реализация grpc profileServer. И при замене возвращаемого значения на nil получаем ошибку: error while marshaling: proto: Marshal called with nil

2019-05-12 14:21 UTC, ZorinArsenij commented on internal/app/delivery/grpc/service/profile/profile.go
> +	return &Nothing{}, err
Аналогичная проблема, как с предыдущим замечанием

2019-05-12 14:23 UTC, ZorinArsenij commented on internal/app/delivery/grpc/service/profile/profile.go
> +	return response, err
А вот это поправил в cbfd426

2019-05-12 14:25 UTC, ZorinArsenij commented on internal/app/delivery/grpc/service/profile/profile.go
> +	response := &GetResponse{
Поправил в 62f744b

2019-05-12 14:28 UTC, ZorinArsenij commented on internal/app/delivery/grpc/service/profile/profile.go
> +func (s *Service) GetByEmail(ctx context.Context, in *GetByEmailRequest) (*GetResponse, error) {
Это ведь реализация сгенерированного интерфейса, поэтому тут также как и там

2019-05-12 14:29 UTC, ZorinArsenij commented on internal/app/delivery/grpc/service/session/session.proto
> +
Убрал в 1a1d0ca

2019-05-12 14:30 UTC, ZorinArsenij commented on internal/app/delivery/http/rest/api/game/handler/game.go
> +		prof, err := (*profileManager).Get(context.Background(),
Странно, но почему-то просто с profileManager не работает. Возможно потому что это grpc client?

2019-05-12 14:32 UTC, ZorinArsenij commented on internal/app/delivery/http/rest/middleware/middleware.go
>  var allowedOrigins = map[string]interface{}{
Отличная идея. Переделал в 31fe088

2019-05-12 14:34 UTC, ZorinArsenij commented on internal/app/infrastructure/repository/memory/chat/chat.go
> +		case chat.InitGlobalMessages:
Согласен, невозможно читать. Поправил в 0259573

2019-05-28 12:02 UTC, merged